## Artificial Neural Networks

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\Soubhik\anaconda3\Anaconda\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\Soubhik\anaconda3\Anaconda\lib\site-packages\pandas\core\arrays\masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


In [2]:
tf.__version__

'2.13.0'

## Part 1 DATA PREPROCESSING

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Encoding categorical data

#### 1. Label Encoding of the Gender column 

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### 2. One Hot Encoding of the Geography column 

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into Training set and Testing dataset

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train = np.array(X_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

## Part 2 Building The ANN

#### 1. Initialising The ANN

In [13]:
ann = tf.keras.models.Sequential()

#### 2. Adding Input Layer or First Hidden Layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### 3. Adding Second Hidden Layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### 4. Adding Output Layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 Training an ANN

### Compiling an ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training an ANN

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 5ms/step - loss: 0.5688 - accuracy: 0.7570
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4423 - accuracy: 0.8039
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4262 - accuracy: 0.8201
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4184 - accuracy: 0.8210
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4127 - accuracy: 0.8244
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4080 - accuracy: 0.8274
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4033 - accuracy: 0.8301
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3991 - accuracy: 0.8309
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3956 - accuracy: 0.8331
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3916 - accura

## Part 4 Predicting the output

#### Make sure to use proper Encoding techniques and the scale as used to train the ANN model

In [19]:
X = [1., 0., 0., 600, 1, 40, 3, 60000, 2, 1, 1, 50000]
X = np.array(X).reshape(1, -1)
X[:, 3:] = sc.transform(X[:, 3:])
print(ann.predict(X))

1/1 [==============================] - 1s 514ms/step
[[0.04895078]]


#### NOTE :
<p> 1. Predict() method expects a 2D array as a format of all inputs. And putting it in double brackets makes it a 2D array. </p>
<p> 2. The country "France" is not taken input as a string but, it is taken input as a [1, 0, 0] as an encoded vector. </p>

## Making Confusion Matrix

#### 1. Predicting Test Results

In [21]:
y_pred = ann.predict(X_test.astype(float))
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 5ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#### 2. Making Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 192  213]]


0.862

## Appendix

In [23]:
help(ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough'))

Help on ColumnTransformer in module sklearn.compose._column_transformer object:

class ColumnTransformer(sklearn.base.TransformerMixin, sklearn.utils.metaestimators._BaseComposition)
 |  ColumnTransformer(transformers, *, remainder='drop', sparse_threshold=0.3, n_jobs=None, transformer_weights=None, verbose=False)
 |  
 |  Applies transformers to columns of an array or pandas DataFrame.
 |  
 |  This estimator allows different columns or column subsets of the input
 |  to be transformed separately and the features generated by each transformer
 |  will be concatenated to form a single feature space.
 |  This is useful for heterogeneous or columnar data, to combine several
 |  feature extraction mechanisms or transformations into a single transformer.
 |  
 |  Read more in the :ref:`User Guide <column_transformer>`.
 |  
 |  .. versionadded:: 0.20
 |  
 |  Parameters
 |  ----------
 |  transformers : list of tuples
 |      List of (name, transformer, columns) tuples specifying the
 |   