In [1]:
import tensorflow as tf

In [2]:
random_gen = tf.random.Generator.from_seed(42)
random_gen.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ]], dtype=float32)>

In [3]:
random_uniform = tf.random.uniform(shape=(2,3))
print(random_uniform)

tf.Tensor(
[[0.5373194  0.5740459  0.7260903 ]
 [0.00179493 0.8287295  0.5112703 ]], shape=(2, 3), dtype=float32)


In [4]:
random_uniform = tf.random.uniform(shape=(2,3), dtype = tf.float32, seed = 12)
print(random_uniform)

tf.Tensor(
[[0.6361525  0.92409146 0.6762773 ]
 [0.50212514 0.9611496  0.8856722 ]], shape=(2, 3), dtype=float32)


In [5]:
random_uniform = tf.random.uniform(shape=(2,3), dtype = tf.float32, seed = 20)
print(random_uniform)

tf.Tensor(
[[0.5690819  0.14772344 0.85629904]
 [0.20141506 0.7484052  0.09923506]], shape=(2, 3), dtype=float32)


In [6]:
random_uniform = tf.random.uniform(shape=(2,3), dtype = tf.float32, seed = 42)
print(random_uniform)

random_uniform_range = tf.random.uniform(shape=(2,3), minval = 0.6, maxval = 0.9, dtype = tf.float32, seed = 42)
print(random_uniform)

tf.Tensor(
[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]], shape=(2, 3), dtype=float32)


In [7]:
tensor = tf.random.shuffle([[1,2],[3,4],[5,6]])
print(tensor)

tensor = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345)
print(tensor)

tensor = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345)
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 4]
 [5 6]
 [1 2]], shape=(3, 2), dtype=int32)


In [8]:
tensor = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345)
print(tensor)

tensor = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345)
print(tensor)

tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [5 6]
 [3 4]], shape=(3, 2), dtype=int32)


In [9]:
a = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345).numpy()
b = tf.random.shuffle([[1,2],[3,4],[5,6]], seed = 2345).numpy()
print(a == b)

[[ True  True]
 [False False]
 [False False]]


In [10]:
string = tf.Variable("this is a string", dtype = tf.string)
print(string)

string_arr = tf.Variable(["this", "is", "a", "string"], dtype = tf.string)
print(string_arr)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'this', b'is', b'a', b'string'], dtype=object)>


##Rank Of tensors

In [11]:
rank_1_tensor = tf.Variable(["This is a string"], dtype = tf.string)
print(rank_1_tensor)

rank_2_tensor = tf.Variable([["This is a string","This is another string"], ["This is test", 'test ok']], dtype = tf.string)
print(rank_2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'This is a string'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'This is a string', b'This is another string'],
       [b'This is test', b'test ok']], dtype=object)>


In [12]:
tf.rank(rank_2_tensor)
print(tf.rank(rank_2_tensor))

print(tf.rank(rank_2_tensor).numpy())

tf.Tensor(2, shape=(), dtype=int32)
2


##Shape Of Tensors

In [13]:
rank_2_tensor.shape

TensorShape([2, 2])

In [14]:
rank_2_tensor = tf.Variable([["Dog","Cat","Cow"], ["eagle", "penguin","house sparrow"]], dtype = tf.string)
print(rank_2_tensor)

print(rank_2_tensor.shape)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'Dog', b'Cat', b'Cow'],
       [b'eagle', b'penguin', b'house sparrow']], dtype=object)>
(2, 3)


In [15]:
rank_2_tensor.numpy()

array([[b'Dog', b'Cat', b'Cow'],
       [b'eagle', b'penguin', b'house sparrow']], dtype=object)

## Changing the shape of tensor

The number of elements of a tensor is the product of the size of all its shapes. Reshaping the tensor has applications in flattening layer of Neural Network.

In [16]:
tensor1 =tf.ones([1,2,3])
print(tensor1)

tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tensor3 = tf.reshape(tensor2, [3,-1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [17]:
tensor1 =tf.ones([2,2,4])
print(tensor1)

# tensor2 =tf.reshape(tensor1, [1,1,2]) ---gives error because 2*2*4 != 1*1*2
# --so, it cant fit all the elements of tensor into this
#print(tensor2) -- error

tensor2 =tf.reshape(tensor1, [1,1,16])
print(tensor2)

tensor3 =tf.reshape(tensor1, [1,1,-1])  #value -1 allows it to calculate the dimension in that place, it will reshape based on number of elements
print(tensor3)                          #this will reshape to [1,1,16]

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 2, 4), dtype=float32)
tf.Tensor([[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(1, 1, 16), dtype=float32)
tf.Tensor([[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(1, 1, 16), dtype=float32)


In [18]:
tshape = tensor.shape #The shape returns a tuple value
print(tshape[0], tshape[1])

3 2


## Evaluating tensors

There will be sometimes when we will be required to evaluate the tensors. In other words, get it's value. Since, tensors represent a partially completed computation, we need to run a session.

In [20]:
tf.__version__

'2.18.0'

In [21]:
with tf.Session() as sess:
  tensor.eval()