# Basic Tensorflow Operations

In [1]:
## For ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
import tensorflow as tf
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_built_with_cuda())
print(tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None))

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2.17.1
True
True


In [3]:
tensor = tf.constant(5)
print(tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
tensor = tf.constant([1,2,3,4,5])
print(tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
tensor = tf.constant([[[1,2,3], [4,5,6]],

                     [[7,8,9], [10,11,12]],

                     [[0.1,0.6,0.9], [1.9,2.3,4.5]],

                     [[10,30,20], [7,80,90]]], dtype = tf.float16
                     )
print(tensor)

tf.Tensor(
[[[ 1.   2.   3. ]
  [ 4.   5.   6. ]]

 [[ 7.   8.   9. ]
  [10.  11.  12. ]]

 [[ 0.1  0.6  0.9]
  [ 1.9  2.3  4.5]]

 [[10.  30.  20. ]
  [ 7.  80.  90. ]]], shape=(4, 2, 3), dtype=float16)


In [6]:
tensor.shape

TensorShape([4, 2, 3])

In [7]:
## Rank of tensor
print(tf.rank(tensor).numpy())

3


In [8]:
print(tensor.ndim)

3


In [9]:
## Immutable Tensor (Not Changed) -> tensor.constant()
tensor = tf.constant([[1,2],[3,4],[5,0]], dtype = tf.float16)
print(tensor)

## Mutable Tensor (Can Be changed) -> tensor.Variable()
tensor = tf.Variable([[1,2],[3,4],[5,0]], dtype = tf.float16)
print(tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 0.]], shape=(3, 2), dtype=float16)
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 0.]], dtype=float16)>


In [10]:
## Change Mutable Tensor values with tensor.assign(value)
print(tensor)
## After Change
tensor[0].assign([[0,12]])
print(tensor)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 0.]], dtype=float16)>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[ 0., 12.],
       [ 3.,  4.],
       [ 5.,  0.]], dtype=float16)>


# tf.math functions (Mathematical Module)

In [13]:
tensor1 = tf.constant([[1,2],[3,4]], dtype = tf.float16)
print(tensor1)

tensor2 = tf.constant([[5,6],[7,8]], dtype = tf.float16)
print(tensor2)

tensor1 + tensor2

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float16)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float16)>

In [14]:
tensor1 = tf.Variable([[1,2],[3,4]], dtype = tf.float16)
print(tensor1)

tensor2 = tf.Variable([[5,6],[7,8]], dtype = tf.float16)
print(tensor2)

tensor1 * tensor2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float16)>


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 5., 12.],
       [21., 32.]], dtype=float16)>

In [15]:
## Add two tensor
tf.add(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float16)>

In [16]:
## Multiplication
tf.multiply(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 5., 12.],
       [21., 32.]], dtype=float16)>

In [21]:
tensor = tf.multiply(tf.constant(5, dtype = tf.float32), tf.constant(6, dtype = tf.float32))
print(tensor)

tf.Tensor(30.0, shape=(), dtype=float32)


In [22]:
tensor = tf.multiply(tf.constant([5,0], dtype = tf.float32), tf.constant(6, dtype = tf.float32))
print(tensor)

tf.Tensor([30.  0.], shape=(2,), dtype=float32)


In [23]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float16)>

In [24]:
print(tensor1 @ tensor2)

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float16)


In [27]:
tensor = tf.multiply(tf.constant([5,0], dtype = tf.float32), tf.constant(6, dtype = tf.float32))
tensor = tf.multiply(tensor, tf.constant([12,0], dtype = tf.float32))
print(tensor)

tf.Tensor([360.   0.], shape=(2,), dtype=float32)


In [29]:
## Broadcasting in Tensor
tensor = tf.multiply(tf.constant([5,0], dtype = tf.float32), tf.constant([[6,1],[2,0]], dtype = tf.float32))
tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[30.,  0.],
       [10.,  0.]], dtype=float32)>

In [31]:
## Trigonometric functions
import math
angles = tf.constant([0.0, math.pi / 2, math.pi])  # Angles in radians
sin = tf.math.sin(angles)
cos = tf.math.cos(angles)
tan = tf.math.tan(angles)

print("Sin:", sin)
print("Cos:", cos)
print("Tan:", tan)

Sin: tf.Tensor([ 0.000000e+00  1.000000e+00 -8.742278e-08], shape=(3,), dtype=float32)
Cos: tf.Tensor([ 1.000000e+00 -4.371139e-08 -1.000000e+00], shape=(3,), dtype=float32)
Tan: tf.Tensor([ 0.0000000e+00 -2.2877334e+07  8.7422777e-08], shape=(3,), dtype=float32)


In [32]:
## Square Root
tf.math.sqrt(tf.constant([[1,4],[9,25]], dtype = tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 5.]], dtype=float32)>

In [33]:
## Natural Logarithm
tf.math.log(tf.constant([[1.0, 4.0], [9.0, 25.0]], dtype = tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.       , 1.3862944],
       [2.1972246, 3.218876 ]], dtype=float32)>

In [34]:
## Rounding Off
x = tf.constant([1.4, 2.6, 3.3])

rounded = tf.math.round(x)  # Rounds to nearest integer
floor = tf.math.floor(x)    # Rounds down
ceil = tf.math.ceil(x)      # Rounds up

print("Rounded:", rounded)
print("Floor:", floor)
print("Ceiling:", ceil)

Rounded: tf.Tensor([1. 3. 3.], shape=(3,), dtype=float32)
Floor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Ceiling: tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [35]:
## Reducing Operations
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype = tf.float32)
sum_all = tf.math.reduce_sum(tensor)
print("Sum of all elements:", sum_all)

sum_axis_0 = tf.math.reduce_sum(tensor, axis=0)
print("Sum along axis 0:", sum_axis_0)

sum_axis_1 = tf.math.reduce_sum(tensor, axis=1)
print("Sum along axis 1:", sum_axis_1)

Sum of all elements: tf.Tensor(21.0, shape=(), dtype=float32)
Sum along axis 0: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Sum along axis 1: tf.Tensor([ 6. 15.], shape=(2,), dtype=float32)


In [37]:
## Statistical Operations
data = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
print("Mean : ", tf.math.reduce_mean(data))
print("\nMean along axis 0: ", tf.math.reduce_mean(data, axis = 0))
print("\nVariance : ", tf.math.reduce_variance(data))
print("\nStandard Deviation : ", tf.math.reduce_std(data))

Mean :  tf.Tensor(3.0, shape=(), dtype=float32)

Mean along axis 0:  tf.Tensor(3.0, shape=(), dtype=float32)

Variance :  tf.Tensor(2.0, shape=(), dtype=float32)

Standard Deviation :  tf.Tensor(1.4142135, shape=(), dtype=float32)


In [42]:
## Comparison
a = tf.constant([2, 4, 6])
b = tf.constant([1, 5, 6])

equal = tf.math.equal(a, b)
greater = tf.math.greater(a, b)
less = tf.math.less(a, b)

print("Equal:", equal)
print("Greater:", greater)
print("Less:", less)
print("\n\n")

equal = tf.math.equal(a, b)
greater = tf.math.greater(a, b)
less = tf.math.less(a, b)

print("Equal:", tf.constant(equal, dtype = tf.bool))
print("Greater:", tf.constant(greater, dtype = tf.bool))
print("Less:", tf.constant(less, dtype = tf.bool))

Equal: tf.Tensor([False False  True], shape=(3,), dtype=bool)
Greater: tf.Tensor([ True False False], shape=(3,), dtype=bool)
Less: tf.Tensor([False  True False], shape=(3,), dtype=bool)



Equal: tf.Tensor([False False  True], shape=(3,), dtype=bool)
Greater: tf.Tensor([ True False False], shape=(3,), dtype=bool)
Less: tf.Tensor([False  True False], shape=(3,), dtype=bool)


#### Special Functions

In [46]:
# Absolute value
abs_value = tf.math.abs(tf.constant([-1.0, -2.0, 3.0]))
print(abs_value,"\n\n")

# Sigmoid function
sigmoid = tf.math.sigmoid(abs_value)

# Softmax
logits = tf.constant([2.0, 1.0, 0.1])
softmax = tf.math.softmax(logits)

print("Absolute Value:", abs_value)
print("Sigmoid:", sigmoid)
print("Softmax:", softmax)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32) 


Absolute Value: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Sigmoid: tf.Tensor([0.73105854 0.880797   0.95257413], shape=(3,), dtype=float32)
Softmax: tf.Tensor([0.6590011  0.24243298 0.09856588], shape=(3,), dtype=float32)
